import React, { Component } from 'react'

import '../../assets/css/general.css';
import './notFound.css';

export default class notFound extends Component {
  render() {
    return (
      <div id="message">
        <div className="Container-center animated bounceIn">
          <img src={ process.env.PUBLIC_URL + '/assets/img/customer_service_150.png' } />
        </div>
        <h2>404</h2>
        <h1>Page Not Found</h1>
        <p style={{ textAlign: 'justify' }} >This is not the web page you are looking for. Please check the URL for mistakes and try again.</p>
        <p style={{ textAlign: 'justify' }} >For any queries, please seek information in <a href="/support">our support page</a>.</p>
        {/* <!-- <h3>Why am I seeing this?</h3> --> */}
        {/* <!-- <p>This page was generated by the Firebase Command-Line Interface. To modify it, edit the <code>404.html</code> file in your project's configured <code>public</code> directory.</p> --> */}
      </div>
    )
  }
}
